spring:
  datasource:
    url: jdbc:mysql://192.168.0.182:3306/intranet
    username: root
    password: Passw0rd
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  codec:
    max-in-memory-size: 8MB

ctrl:
  hostname: 192.168.3.5
  port: 8002

