spring:
  datasource:
    url: jdbc:mysql://localhost:3306/intranet
    username: root
    password: tnpdtr
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  codec:
    max-in-memory-size: 8MB

ctrl:
  hostname: localhost
  port: 8080
