spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: dbuser
    password: dbpass
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
