spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

ctrl:
  hostname: 192.168.3.5
  port: 8000
  token: "{5BE619BF-BE46-472B-B4B1-024FA7CF4725}"
  auth: "Basic V0VCU1RQOlN0ZWVsMjAyMiE="

logFolder: /Users/LaincoMini/IdeaProjects/CTRLProxy/logs