spring:
  datasource:
    url: jdbc:mysql://192.168.0.202:3306/intranet
    username: intranet
    password: lainco
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  codec:
    max-in-memory-size: 8MB

ctrl:
  hostname: 192.168.1.157
  port: 8002
