spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

ctrl:
  hostname: 192.168.3.5
  port: 8002
  token: "{3F2DB33F-902E-45BC-98C3-C5F18F7019AE}"
  auth: "Basic V0VCU1RQOlN0ZWVsMjAyMiE="

logFolder: logs

server:
  port: 8081

queries:
  report1:
    connection: Produit
    sql: |
      SELECT IS17DODE.FI16DOCCOD, IS16DOEN.FI16DOCSTA,
             IS17DODE.FI17DOCLIG, IS17DODE.FI17DOCORD,
             IS16DOEN.FI16DATINS, IS17DODE.FI16TYPCOD,
             IS17DODE.FI17DOCMAI, IS17DODE.FI17LIGMAI,
             IS16DOEN.FI16FACCOD, IS17DODE.FI17PRJCOD,
             IS17DODE.FI17ACTCOD, ES02ACTI.FE02ACTDES,
             IS17DODE.FI17DESLIG, IS17DODE.FI17QTESUS,
             IS17DODE.FI17QTETRT, IS17DODE.FI17PRX001,
             IS17DODE.FI17QTEANN, IS17DODE.FI17TOT001 FROM  "ci001-is17dode"  IS17DODE 
             LEFT OUTER JOIN  "ci001-is16doen"  IS16DOEN ON 
             (IS16DOEN.FI16TYPCOD = IS17DODE.FI16TYPCOD) 
             AND (IS16DOEN.FI16DOCCOD = IS17DODE.FI16DOCCOD) 
             LEFT OUTER JOIN  "//ctrl-lainco-0/ctrl/projet/data/smigg.add"."ci001-es02acti"  ES02ACTI ON 
             (ES02ACTI.FE02ACTCOD = IS17DODE.FI17ACTCOD) 
             WHERE
                IS17DODE.FI16TYPCOD IN ('BSP','RSP','FSP','BCS','BCF','RCF','FFF','BSP','RSP','FSP','BCS','BCF','RCF','FFF') 
                AND IS17DODE.FI17PRJCOD = ? ;